name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  Dev_Deployment:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: echo "hello dev"
        
  deploy-qa:
    name: Deploy to QA
    needs: Dev_Deployment
    runs-on: ubuntu-latest
    if: needs.Dev_Deployment.result == 'success'
    environment: Qa
    steps:
      - name: deploy
        run: echo "hello QA"
